---
upload_path: "/static/uploads"
frontmatter_file_url_template: "/uploads"
body_file_url_template: "/uploads"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  portfolio:
    default_front_matter_template: portfolio
version: '0.28'
